export const ADD_USER = "ADD_USER";
export const MODIFY_USER = "MODIFY_USER";
export const LOGOUT_USER = "LOGOUT_USER";
export const CHECK_USER = "CHECK_USER";
export const AJOUTER_COMMANDER = "AJOUTER_COMMANDER";
export const VALIDER_COMMANDE = "VALIDER_COMMANDE";
export const READ_NOTIFICATION = "READ_NOTIFICATION";
export const FETCH_ALL_RESTAURANT = "FETCH_ALL_RESTAURANT";
