export const ADD_USER = "ADD_USER";
export const MODIFY_USER = "MODIFY_USER";
export const DELETE_USER = "DELETE_USER";
export const CHECK_USER = "CHECK_USER";
export const COMMANDER_REPAS = "COMMANDER_REPAS";
export const VALLIDER_COMMAND = "VALLIDER_COMMAND";
export const READ_NOTIFICATION = "READ_NOTIFICATION";
