export const ADD_USER = "ADD_USER";
export const MODIFY_USER = "MODIFY_USER";
export const DELETE_USER = "DELETE_USER";
export const CHECK_USER = "CHECK_USER";
export const AJOUTER_COMMANDER = "AJOUTER_COMMANDER";
export const VALIDER_COMMANDE = "VALIDER_COMMANDE";
export const READ_NOTIFICATION = "READ_NOTIFICATION";
